openapi: 3.0.0
info:
  title: EduRoute
  contact:
    name: Saad
    email: saad.elm2002@gmail.com
  version: '1.0'
servers:
- url: https://eduroute-api.onrender.com/api/v1
  variables: {}
paths:
  /auth/register:
    post:
      tags:
      - Authentication
      summary: register
      description: ''
      operationId: register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/registerrequest'
              - example:
                  name: saad
                  email: saad1@gmail.com
                  password: NewPassword
            example:
              name: saad
              email: saad1@gmail.com
              password: NewPassword
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
      - Authentication
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/loginrequest'
              - example:
                  email: saad@gmail.com
                  password: NewPassword
            example:
              email: saad@gmail.com
              password: NewPassword
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /courses/:
    post:
      tags:
      - Courses
      summary: createCourse
      operationId: createCourse
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/createCourseRequest'
              - example:
                  instructor: astro
                  course_name: course_name 1
                  course_status: in progress
            example:
              instructor: astro
              course_name: course_name 1
              course_status: in progress
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    get:
      tags:
      - Courses
      summary: getAllCourses
      operationId: getAllCourses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
  /courses/{id}:
    get:
      tags:
      - Courses
      summary: getSingleCourse
      operationId: getSingleCourse
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    patch:
      tags:
      - Courses
      summary: updateCourse
      operationId: updateCourse
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/updateCourseRequest'
              - example:
                  instructor: saad
                  course_name: course_name 1
                  course_status: in progress
            example:
              instructor: saad
              course_name: course_name 1
              course_status: in progress
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
    delete:
      tags:
      - Courses
      summary: deleteCourse
      operationId: deleteCourse
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
components:
  schemas:
    registerrequest:
      title: registerrequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: saad
        email: saad1@gmail.com
        password: NewPassword
    loginrequest:
      title: loginrequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: saad@gmail.com
        password: NewPassword
    createCourseRequest:
      title: createCourseRequest
      required:
      - instructor
      - course_name
      - course_status
      type: object
      properties:
        instructor:
          type: string
        course_name:
          type: string
        course_status:
          type: string
      example:
        instructor: astro
        course_name: course_name 1
        course_status: in progress
    deleteCourseRequest:
      title: deleteCourseRequest
      required:
      - instructor
      - course_name
      - course_status
      type: object
      properties:
        instructor:
          type: string
        course_name:
          type: string
        course_status:
          type: string
      example:
        instructor: astro 2
        course_name: course_name 1
        course_status: in progress
    updateCourseRequest:
      title: updateCourseRequest
      required:
      - instructor
      - course_name
      - course_status
      type: object
      properties:
        instructor:
          type: string
        course_name:
          type: string
        course_status:
          type: string
      example:
        instructor: saad
        course_name: course_name 1
        course_status: in progress
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Authentication
  description: ''
- name: Courses
  description: ''